### ISSUE TITLE
etags break the instance validator

### ISSUE THREAD

**Issue by bsimmons-onboard** [google/digitalbuildings#1006]
**Describe the bug**
The instance validator doesn't work on entities that include etags.

**To Reproduce**
minimal.yaml
`6a99999c-05c8-4a01-8c4a-99f256be4c7f:`
`  code: Test-Building`
`  etag: d7b7777e`
`  type: FACILITIES/BUILDING`

`python instance_validator.py -i minimal.yaml`

`while parsing a mapping
unexpected key not in schema 'etag'
  in "<unicode string>", line 3, column 1:
      etag: d7b7777e
    ^ (line: 3)`

**OS:**
Ubuntu

**Comment by trav3711** [comment]
This has to do with a conflict between the `CONFIG_METADATA` operation and the existence of etags. Looking into it.

**Comment by charbull** [comment]
@trav3711 @bsimmons-onboard you need to update the this part:

```
CONFIG_METADATA:
  operation: UPDATE
```

https://github.com/google/digitalbuildings/blob/master/ontology/docs/building_config.md#update

**Comment by bsimmons-onboard** [comment]
@charbull, I can confirm that adding the UPDATE operation allowed me to run the instance_validator on an building_config with etags.

**Comment by charbull** [comment]
cool, thank you for confirming. closing for now, feel free to reopen if needed.
