### ISSUE TITLE
Ontology explorer not validating field names

### ISSUE THREAD

**Issue by pisuke** [google/digitalbuildings#1011]
**Describe the bug**
When running the Ontology Explorer, option 3 Validate a field name, I get only "False" results.

**To Reproduce**
1. `python3 explorer.py`
2. Select option 3 and then HVAC or another namespace
3. write `run_status`
4. output: `run_status is defined in HVAC: False`

I would have expected this to match. I've tried this with many fields that I know exist and it always fails.

**Expected behavior**
The expected behaviour would be to match the existing ontology field.

**Screenshots**
```
How would you like to query DBO
1: Get fields for a type name
2: Get types for a list of fields
3: Validate a field name
q: quit

Please select an option: 3
Enter a namespace(leave blank for global): HVAC
Enter a field name to validate: run_status
run_status is defined in HVAC: False
```

**OS (please complete the following information):**
Linux 

**Additional context**
Nothing else.

**Comment by mschulze17** [comment]
Closing here in Github, resolved in internally tracked bug
