### ISSUE TITLE
DBO Validation Error: Blank 'etag:' field being generated within building_config.yaml

### ISSUE THREAD

**Issue by Ry-Krbs** [google/digitalbuildings#1015]
**IMPORTANT**
DO NOT INCLUDE ANY PROJECT-SPECIFIC INFORMATION IN THIS TICKET!
ANY PROJECT-SPECIFIC CONTEXT (E.G. BUILDING CONFIG INPUTS) SHOULD BE
EMAILED DIRECTLY TO: digitalbuildings-support@googlegroups.com

PLEASE REFERENCE THIS ISSUE LINK IN YOUR EMAIL TO THAT GROUP

**Describe the bug**
When running dbo validator, we come across an error:

```
58 findings.

[INFO]  Ontology loaded.
[INFO]  Loading config files: ['sites/XX-XXX-XXX/dbo/building_config.yaml']   
[INFO]  Starting syntax validation.
[INFO]  Opening file: sites/XX-XXX-XXX/dbo/building_config.yaml.
while parsing a mapping
unexpected key not in schema 'etag'
  in "<unicode string>", line 7, column 1:
      etag: ''
    ^ (line: 7)
```
This appears to be due to blank "etag:" fields being present within the building_config.yaml

Is this 'etag:' field generated by ABEL and is this required at this time?

To proceed, all 'etag:' references were removed from the building_config and this cleared the error.

**Comment by trav3711** [comment]
@Ry-Krbs This error is probably coming from the fact that your `config_metadata` operation is `INITIALIZE`. Building Configs under the `INITIALIZE` operation are not expected to have etags.

You can either remove all etags or change your config metadata operation to `UPDATE` or `EXPORT`.

**Comment by charbull** [comment]
https://github.com/google/digitalbuildings/blob/master/ontology/docs/building_config.md#initialize

https://github.com/google/digitalbuildings/blob/master/ontology/docs/building_config.md#update

**Comment by charbull** [comment]
@Ry-Krbs closing this for now, please re-open if needed
