### ISSUE TITLE
TELEMETRY VALIDATOR SHOWING MISSING POINTS FOR POINTS PRESENT ON CLOUD

### ISSUE THREAD

**Issue by darshanjain12** [google/digitalbuildings#1022]
**IMPORTANT**
DO NOT INCLUDE ANY PROJECT-SPECIFIC INFORMATION IN THIS TICKET!
ANY PROJECT-SPECIFIC CONTEXT (E.G. BUILDING CONFIG INPUTS) SHOULD BE
EMAILED DIRECTLY TO: digitalbuildings-support@googlegroups.com

PLEASE REFERENCE THIS ISSUE LINK IN YOUR EMAIL TO THAT GROUP

**Describe the bug**
The telemetry validator is showing missing points for the points actually present.

**To Reproduce**
1. Run the command: python3 toolkit.py -i filename -v -d folderpath -s subscription
2. Check the telemetry validation report
3. Scroll down to the telemetryMessageErrors inside that look in missing points.

**Expected behavior**
All expected points should be validated as all points present in UDMI.

**Screenshots**
![image](https://user-images.githubusercontent.com/104188629/236664164-a2989b7a-8907-4691-8145-a00ac095494d.png)

![image](https://user-images.githubusercontent.com/104188629/236665116-a05d9316-c07b-46ca-aa5a-da229b26c1a4.png)

![image](https://user-images.githubusercontent.com/104188629/236791956-5f9a2421-d873-4935-b2ae-e55196bfd242.png)

**Additional context**
We have set up our site model  as per UDMI standard

**Comment by sypks** [comment]
Hello @darshanjain12,

Thank you for all the information :).
It appears that three of the five points in the payload have a name mismatch with the building config used.
That doesn't explain why why the remaining 2 points were not picked up.

Could you please provide the full telemetry report json block containing the snippet in the middle image?

Best,
shane

**Comment by darshanjain12** [comment]
Hi Please find the attached the full telemetry validation report.
I hope this will help in finding the root cause and solve it.

[2023_05_12T12_42_39Z_telemetry_validation_report.zip](https://github.com/google/digitalbuildings/files/11504572/2023_05_12T12_42_39Z_telemetry_validation_report.zip)

**Comment by trav3711** [comment]
Hi @darshanjain12 

Have you tried running the validator again recently? I can't seem to reproduce the error. Our source code for the validator appears to be correct so I don't think this is a bug in our application.

**Comment by darshanjain12** [comment]
Hi @trav3711 i tried running the validator again but i am getting the same issue. Please suggest what we can do to get clean reports.

**Comment by trav3711** [comment]
@darshanjain12 one thing is your building config doesn't seem to have units. For fields that have no units, the proper notation is `no-units: no_units`

**Comment by darshanjain12** [comment]
Hi @trav371

> @darshanjain12 one thing is a lot of fields for the LGRP types in your building config don't seem to have units. For fields that have no units, the proper notation is `no-units: no_units`
> 
> should look something like:
> 
> ```
> counter:
>       present_value: "counter.present_value"
>       units:
>         no-units: "no_units"
> ```

Hi @trav3711 we now did the required changes still we are facing the same issue

**Comment by trav3711** [comment]
Hi @darshanjain12 sorry for the delay, but I am still trying to debug this issue. Several members of our team have verified that we don't have bugs in our code. Have you run `git pull` on a copy of your local master branch to ensure you are running the latest version of our tool?

**Comment by darshanjain12** [comment]
Hi @trav3711 i did run git pull on a copy of my local master branch. Still I am facing the same issue. Can you share your generated reports with me?

**Comment by trav3711** [comment]
Closing this issue as it is a problem with the subscription messages rather than tooling source code.
