### ISSUE TITLE
DBO Explorer raising error "Inherited Fields must be expanded to query fields"

### ISSUE THREAD

**Issue by adelin-diac** [google/digitalbuildings#1043]
**IMPORTANT**
DO NOT INCLUDE ANY PROJECT-SPECIFIC INFORMATION IN THIS TICKET!
ANY PROJECT-SPECIFIC CONTEXT (E.G. BUILDING CONFIG INPUTS) SHOULD BE
EMAILED DIRECTLY TO: digitalbuildings-support@googlegroups.com

PLEASE REFERENCE THIS ISSUE LINK IN YOUR EMAIL TO THAT GROUP

**Describe the bug**
DBO Explorer returning "Type XX_XX... has not been expanded" when running from a branch in my fork. Branch includes all the changes to the DBO awaiting to be merged into main branch. [Link to branch](https://github.com/adelin-diac/digitalbuildings/tree/hw_fre_changes). 

**To Reproduce**
1. Follow steps to initiate DBO Explorer. (Activate tooling virtual environment, install dependencies)
2. Run `python explorer.py` from `..\digitalbuildings\tools\explorer\`. Error also occurs when running with a `path/to/modified/ontology/types/folder` argument (`--modified-ontology-types`).
3. Select Option 1 or 2. Option 1: `Get fields for a type name`. Option 2: `Get types for a list of fields`.
4. Enter either type name or fields list, depending on chosen option.
5. See error

**Expected behavior**
When selecting option to view types for a list of fields, the explorer tool should output a list of types and their score for matching with the inputted list of fields.

![image](https://github.com/google/digitalbuildings/assets/105500899/c0b06fe6-797e-4daf-b9e1-09f28e802e22)
![image](https://github.com/google/digitalbuildings/assets/105500899/e871b19f-b392-4bb0-823f-980384856242)

**OS (please complete the following information):**
windows

**Comment by trav3711** [comment]
Hi @adelin-diac this looks to be a problem with your ontology. Have you tried running the Ontology Validator on your modified ontology?

@tasodorff

**Comment by adelin-diac** [comment]
Hi @trav3711 , I've just run the validator now and turns out there was an abstract type defined twice. Changing it fixed it for me. Thank you.
