### ISSUE TITLE
Typos in entity type names

### ISSUE THREAD

**Issue by shambergoldstein** [google/digitalbuildings#1058]
Typo in HVAC entity type `DWST_CHDT_SWTC_CPC`, should be `DWST_CWDT_SWTC_CPC`

**Comment by cstirdivant** [comment]
We should augment the validation tools to check that the type name string matches the implemented abstract types. Additionally, we will need to retroactively fix type names and need to determine the downstream ramifications of this.

**Comment by cstirdivant** [comment]
Also a typo in `TST_PCHWDY_SCHWDT_SCHWISOVPM_TS6X`

**Comment by trav3711** [comment]
Update Instance validator to check type name components map to abstract types.
