### ISSUE TITLE
Ontology Explorer - Surface all field names from a list of subfields

### ISSUE THREAD

**Issue by cstirdivant** [google/digitalbuildings#1100]
I want to be able to pass in a list (with arbitrary delimiters) of subfields and want to see all the existing field names that use those subfields.

For example, if I pass in a list [supply, water, setpoint] the tool would return: supply_water_temperature_setpoint, chilled_supply_water_temperature_setpoint, heating_water_supply_temperature_setpoint, etc.

**Comment by trav3711** [comment]
The above PR does add the desired feature. However some kind of error handling could be added in order to surface invalid subfields. Will add internally, and will keep issue open to track.
