### ISSUE TITLE
[Bug] Instance Validator when is called from a different folder

### ISSUE THREAD

**Issue by charbull** [google/digitalbuildings#125]
There is a path bug in the instance validator when it is called from a different folder.

To Reproduce:
```
python3 ./tools/validators/instance_validator/instance_validator.py -i ./ontology/yaml/resources/pis.yaml
```
output:
```
Validator starting ...

Passed syntax checks!
Generating universe ...
UnitUniverse undefined in ConfigUniverse
FieldUniverse undefined in ConfigUniverse
Universe generated successfully
Invalid namespace: FACILITIES
Invalid type
ch-zrh-eurd is not a valid instance
```

file content example:

```
ch-zrh-eurd:
  type: FACILITIES/BUILDING
  id: 17400aae-c49a-49d4-a585-8a234f29532d

# Floor 08
ch-zrh-eurd-08:
  type: FACILITIES/FLOOR
  id: 36092aaf-4a0b-4961-b209-6d01f823b440
  connections:
    ch-zrh-eurd: CONTAINS```

**Comment by mschulze17** [comment]
@charbull, mind confirming this is fixed?

**Comment by charbull** [comment]
@mschulze17  I am not sure, we need to try it out.

**Comment by dplute** [comment]
I was able to run the instance validator from any folder, using either a relative or absolute path to instance_validator.py.  However, I had to adjust the input data to get validation to pass:
- Change the entity names to uppercase.
- Remove the ``` at the end.
- Move the building config file out of the ontology/yaml/resources folder.

**Comment by mschulze17** [comment]
@charbull, assigning back to you following Daley's note above
