### ISSUE TITLE
Generating an instance

### ISSUE THREAD

**Issue by david-waterworth** [google/digitalbuildings#132]
How do you create an instance in RDF? I created a building config YAML file following https://github.com/google/digitalbuildings/blob/master/ontology/docs/building_config.md i.e.

```
# Building
UK-LON-S2:
  type: FACILITIES/BUILDING
  id: FACILITIES/123456
```

Running the validator on this works fine. But then I assumed you could pass this file to the `rdf_generator` but the following

`python rdfformat/rdf_generator.py --input=/home/david/dev/digitalbuildings/.data/building_config.yaml --output=/home/david/dev/digitalbuildings/.data/digital_buildings.rdf`

throws the error

> NotADirectoryError: [Errno 20] Not a directory: '/home/david/dev/digitalbuildings/.data/building_config.yaml/FACILITIES/entity_types/Facilities.yaml'

The help indicates:

> rdfformat/rdf_generator.py:
>   --input: The path of the input file
>   --output: The path of the output file

But it actually appears to expect  `--input` to be the root folder of the ontology (which matches the readme)

Are there any tools to convert a building config into say a TTL file like Brick?

**Comment by charbull** [comment]
Hi @david-waterworth 

The RDF generator for now takes the ontology types, the ones that are here: [https://github.com/google/digitalbuildings/tree/master/ontology/yaml/resources](https://github.com/google/digitalbuildings/tree/master/ontology/yaml/resources).

We dont support that yet to generate an rdf file from the configuration file.

You can however, follow this example to generate an instance:
[https://github.com/google/digitalbuildings/tree/master/ontology/rdf/example](https://github.com/google/digitalbuildings/tree/master/ontology/rdf/example)

Hope that helps,

Thank you

**Comment by david-waterworth** [comment]
Thanks @charbull
