### ISSUE TITLE
Provide proper end when multiple YAML documents in file

### ISSUE THREAD

**Issue by corymosiman12** [google/digitalbuildings#146]
https://github.com/google/digitalbuildings/blob/d884a086cb9337631a5d1a8127df7ce17be4b7a8/ontology/yaml/resources/fields/telemetry_fields.yaml#L175-L176

Parsers have issue with the above.  Should have:
```yaml
...
---
```

**Comment by mschulze17** [comment]
Reviewed, deprecated, this has been fixed
