### ISSUE TITLE
Mappings

### ISSUE THREAD

**Issue by amirlad** [google/digitalbuildings#154]
Hello,

I am trying to understand the ontology. However, I found it a little bit complicated but it seems to be interesting.

I would like to know if there are any mappings to Brick, SSN, or SAREF, this may enhance my understanding of the ontology.

Thank you,
Amir

**Comment by charbull** [comment]
Hi Amir,

There is an rdf ontology version if it helps.
We don't provide a mapping to the other ontologies.

**Comment by mschulze17** [comment]
Closed, there is no issue
