### ISSUE TITLE
Instance validator thread keep listening after the report is published

### ISSUE THREAD

**Issue by charbull** [google/digitalbuildings#176]
**Describe the bug**
Instance validator thread keep listening after the report is published

**To Reproduce**
run the validator on the s2 file

**Expected behavior**
After the report is published the instance validator needs to exit

**Comment by mschulze17** [comment]
@charbull - can we get an update on this Issue?

**Comment by charbull** [comment]
@mschulze17 this has not been fixed, it will be good to bring it to our next sprint.
