### ISSUE TITLE
Add option to validate an entire directory of YAML files

### ISSUE THREAD

**Issue by nkilmer** [google/digitalbuildings#177]
We currently support users providing the --input parameter multiple times to validate multiple individual files. It would also be useful to have an --input-dir parameter that lets the user validate an entire directory without individually specifying all the files contained within.

**Comment by mschulze17** [comment]
@charbull, should this be re-assigned?

**Comment by charbull** [comment]
I think it is supported, Travis can check please ?

**Comment by trav3711** [comment]
@charbull This functionality is not currently supported.

**Comment by charbull** [comment]
Thank you for looking !
It needs to be reassigned. Probably a P3 for now ?

**Comment by mschulze17** [comment]
Converted to Carson Backlog item, closing
