### ISSUE TITLE
Distinction between SubField/Measurement/* and Unit/*

### ISSUE THREAD

**Issue by corymosiman12** [google/digitalbuildings#181]
The classes under `SubField/Measurement` and `Unit` are equivalent sets (i.e. all classes are same).  Why is this?

Additionally, in Protege, when I look at `Unit/Concentration` (usages), `parts_per_million` comes up (and confirmed in RDF):

![image](https://user-images.githubusercontent.com/28991233/102842052-547b9100-43c3-11eb-8ef3-0fca62441a68.png)

However, when I then click on the  Concentration below:

<img width="320" alt="Screen Shot 2020-12-21 at 7 33 33 PM" src="https://user-images.githubusercontent.com/28991233/102842156-8db40100-43c3-11eb-95bd-3bc521060be0.png">

It actually resolves to the `Subfield/Measurement/Concentration` class.  Is this expected? Can others reproduce? Why does this happen?

**Comment by charbull** [comment]
Hi @corymosiman12 Units and Measurements are not equivalent, they have two different uris
It is coming from yaml model here:
* https://github.com/google/digitalbuildings/blob/master/ontology/yaml/resources/units/units.yaml
* https://github.com/google/digitalbuildings/blob/master/ontology/yaml/resources/subfields/subfields.yaml

The RDF conversion, tries to stay as much conformant as possible to the yaml version.

**Comment by mschulze17** [comment]
@charbull - can we get an update?

**Comment by charbull** [comment]
@mschulze17 backlog, P3 bug

**Comment by tasodorff** [comment]
in the backlog
