### ISSUE TITLE
IBR Demo export button: download not defined

### ISSUE THREAD

**Issue by drewdepriest** [google/digitalbuildings#190]
**Describe the bug**
In IBRSDK demo, trying to export selected floors as separate IBRs. Dev tools shows _Uncaught ReferenceError: download is not defined at HTMLButtonElement._ Files do not download.

**To Reproduce**
1. In IBR demo, upload the sample SVL IBR file.
2. Click the _Export_ toggle.
3. Select multiple floors from the _us-svl-tc2-2_ object in sidebar.
4. Open Chrome dev tools with view of _Console_.
5. At bottom of sidebar, enter a filename and click the _Save and Export to IBR_ button.
6. See error in _Console_.

**Expected behavior**
I would expect multiple, independent IBRs consistent with the floors checked to automatically generate and download from the browser.

**Screenshots**
<img width="1789" alt="Screen Shot 2021-01-03 at 11 33 46 AM" src="https://user-images.githubusercontent.com/1335002/103484866-99d29200-4db7-11eb-8815-81883391bc45.png">

**OS (please complete the following information):**
MacOS Catalina v10.15.7
VS Code 1.51.1
Node v14.15.1

**Additional context**
I tried to troubleshoot by moving script further down index.html to see if it needed to load after the button, with no luck. Based on my limited exposure to Node, my best guess is that the index file is having an issue calling the download() function with three params in the _got_ module.

Perhaps I have also missed an instruction elsewhere in the repo and simply don't have my local instance configured properly.

**Comment by kswang2400** [comment]
Thanks for reporting this issue, Drew! I've opened https://github.com/google/digitalbuildings/pull/196 to fix it, will land it shortly. :)

**Comment by manishnc** [comment]
Hello charbull and Everybody ,

I found index.html (/ibr/examples/html/index.html ) is not working. It is not showing checkboxes when i am uploading files and nither it showing GUI. 

First issue :  sudo npm run build  (this command is showing below error) , I have checked installed npm version is 3.5.2 

![image](https://user-images.githubusercontent.com/78270452/118201849-5e745e00-b450-11eb-9840-3e43c2ec33b5.png)

Second issue: 

/ibr/examples/html/index.html page is also working as per desire. I am not sure am I doing some mistake please guide correct procedure which is little urgent. Please help me. 



![image](https://user-images.githubusercontent.com/78270452/118199465-1b63bc00-b44b-11eb-8970-8f16c34bb321.png)
[](url)

**Comment by manishnc** [comment]
Hello charbull and Everybody ,

I found index.html (/ibr/examples/html/index.html ) is not working. It is not showing checkboxes when I am uploading files and neither it showing GUI. 

First issue :  sudo npm run build  (this command is showing below error) , I have checked installed npm version is 3.5.2 

![image](https://user-images.githubusercontent.com/78270452/118201849-5e745e00-b450-11eb-9840-3e43c2ec33b5.png)

Second issue: 

/ibr/examples/html/index.html page is also working as per expected. Please guide correct procedure which is little urgent. Please help me. 



![image](https://user-images.githubusercontent.com/78270452/118199465-1b63bc00-b44b-11eb-8970-8f16c34bb321.png)
[](url)

**Comment by manishnc** [comment]
Hello charbull and Everybody ,

I found index.html (/ibr/examples/html/index.html ) is not working. It is not showing checkboxes when I am uploading files and neither it showing GUI. 

First issue :  sudo npm run build  (this command is showing below error) , I have checked installed npm version is 3.5.2 


![image](https://user-images.githubusercontent.com/78270452/118202862-b01de800-b452-11eb-91c5-04f6fbd62ee4.png)

Second issue: 

/ibr/examples/html/index.html page is also working as per expected. Please guide correct procedure which is little urgent. Please help me. 



![image](https://user-images.githubusercontent.com/78270452/118199465-1b63bc00-b44b-11eb-8970-8f16c34bb321.png)
[](url)

**Comment by manishnc** [comment]
Hello charbull and Everybody ,

I found index.html (/ibr/examples/html/index.html ) is not working. It is not showing checkboxes when I am uploading files and neither it showing GUI. 

First issue :  sudo npm run build  (this command is showing below error) , I have checked installed npm version is 6.14.13


![image](https://user-images.githubusercontent.com/78270452/118202862-b01de800-b452-11eb-91c5-04f6fbd62ee4.png)

Second issue: 

/ibr/examples/html/index.html page is also working as per expected. Please guide correct procedure which is little urgent. Please help me. 



![image](https://user-images.githubusercontent.com/78270452/118199465-1b63bc00-b44b-11eb-8970-8f16c34bb321.png)
[](url)
