### ISSUE TITLE
Question: What is the Carson ontology?

### ISSUE THREAD

**Issue by drewdepriest** [google/digitalbuildings#200]
[Section 3 of the RDF Example README](https://github.com/google/digitalbuildings/tree/master/ontology/rdf/example#3-instantiate-the-ontology-model-with-the-generated-code) alludes to the "Carson ontology" when instantiating business logic.

**Simple question** - where can one learn more about said Carson ontology?

I have exhausted the requisite 30 minutes of phrase searching across the broader web, and have read @charbull's PoCBoC paper twice. "Carson" doesn't appear there either.

The example in the README appears it could be a BAS SDK, not unlike OLGA or the ALC SDK I've worked with in the past. A way of representing hierarchical relationships in the BAS as objects, of sorts.

Curiosly,
Drew

**Comment by charbull** [comment]
Hi @drewdepriest there is no `Carson` Ontology, I updated the text to Digital Buildings Ontology
Thanks for the question.

The ontology is here:
https://github.com/google/digitalbuildings/tree/master/ontology

Let us know if you have any questions
