### ISSUE TITLE
The instance validator validates connections that are not in defined within the connections.yaml file 

### ISSUE THREAD

**Issue by oli-barker** [google/digitalbuildings#217]
**Describe the bug**
Should the instance validator kick up an error when connections are used in the building_config.yaml file that are not defined within the ~/ontology/yaml/resources/connections/connections.yaml file within the ontology?

**To Reproduce**
1. within the building_config.yaml file enter in a connection that is not within defined within the connections file. In the example below I have used "BOB" as a connection that isn't defined in the connections.yaml file.

ZONE-202:
  type: HVAC/ZONE_HVAC
  id: CDM/110111
  connections:
    UK-LON-X1_L02: CONTAINS 
    AHU-1: BOB

2. then run the validator commands:

python3 instance_validator.py --input path/to/building_config.yaml

3. This still outputs a valid response:

*$ python3 instance_validator.py --input /media/sf_shared/test.yaml

Validator starting ...

Generating universe ...
Universe generated successfully
Validating syntax please wait ...
Opening file: /media/sf_shared/test.yaml, please wait ...
Validating entities ...
All entities validated

**Expected behavior**
I expected the validator to fail as "BOB" is not defined as a connection in the connections.yaml

**OS (please complete the following information):**

OS - Ubuntu 20.04.02 LTS
Repository cloned from master on 4/3/2021

**Comment by mschulze17** [comment]
@charbull - is this resolved?

**Comment by charbull** [comment]
Not yet, P2 bug

**Comment by tasodorff** [comment]
moved internally to backlog

**Comment by trav3711** [comment]
This behavior is already implemented.
