### ISSUE TITLE
Tool to extract the type of the device based on set of point name and entity type

### ISSUE THREAD

**Issue by conroy-chee** [google/digitalbuildings#224]
The instance_validator.py is the python script to validate a building ontology YAML file. In the YAML file, the type of device is compulsory e.g. FCU_DFSS_CSP_CHWDC. This instance_validator.py will validate whether the point name list for a respective device fulfills the requirement.

It is advisable to build a tool to extract the type of a device based on the list of point names of the device and the entity type it belongs to. 

For example, if a user runs the tool to get the device type for FCU-11 with a list of points names e.g. pn1, pn2. The user would just need to pass in "FCU" entity type together with all the point names as the arguments e.g. tool --entity_type="FCU" --point_name="pn1, pn2". The output will retrieve the type e.g. FCU_DFSS_CSP_CHWDC.

**Comment by charbull** [comment]
@conroy-chee can you please remove the pdf, it contains private information that are not meant to be shared here.

Thank you

**Comment by tasodorff** [comment]
@conroy-chee in progress, see here for preview: https://github.com/google/digitalbuildings/pull/244

**Comment by mschulze17** [comment]
Deprecated by Explorer
