### ISSUE TITLE
Enhancement on ontology_match_lib.py

### ISSUE THREAD

**Issue by conroy-chee** [google/digitalbuildings#250]
Ontology_match_lib.py is great to find the closest type with the proximity level e.g. NONE, CLOSE, INCOMPLETE and EXACT. May I suggest to enhance the tool so it can display the closest set of abstract types? 

For example, a FCU consist of the following point:

real_fields = {
    "chilled_water_valve_percentage_command",
    "chilled_water_valve_percentage_sensor",
    "discharge_fan_run_command",
    "discharge_fan_run_status",
    "schedule_run_command",
    "zone_air_temperature_sensor",
    "zone_air_temperature_setpoint",
}
fit = ont.find_best_fit_type(real_fields, 'HVAC', 'FCU')

When I ran the tool, it would display the following result:

MATCH COMPLETENESS: 'INCOMPLETE'
MATCHED TYPE: 'FCU_DFSS_DFVSC_ZTC_CHWZTC_DTC_CO2C'

ACTUAL FIELDS                             TYPE FIELDS                               REQUIRED                                  
=======================================   =======================================   =======================================   
chilled_water_valve_percentage_command    chilled_water_valve_percentage_command    True                                      
chilled_water_valve_percentage_sensor     chilled_water_valve_percentage_sensor     False                                     
                                          discharge_air_temperature_sensor          True                                      
                                          discharge_air_temperature_setpoint        True                                      
discharge_fan_run_command                 discharge_fan_run_command                 True                                      
discharge_fan_run_status                  discharge_fan_run_status                  True                                      
                                          discharge_fan_speed_percentage_command    True                                      
schedule_run_command                      schedule_run_command                      False                                     
                                          zone_air_co2_concentration_sensor         True                                      
                                          zone_air_co2_concentration_setpoint       True                                      
zone_air_temperature_sensor               zone_air_temperature_sensor               True                                      
zone_air_temperature_setpoint             zone_air_temperature_setpoint             True                                      

The closest type it returned was FCU_DFSS_DFVSC_ZTC_CHWZTC_DTC_CO2C (a new type created by me for another FCU device). Due to the match completeness was ‘INCOMPLETE’, so it still did not fulfil the requirement. Upon looking for the most appropriate abstract types, I could get CHWVM, DFSS and ZTC to create the following new type:

FCU_DFSS_CHWVM_ZTC:
  id: "8815310973633036290"
  description: "tbc"
  is_canonical: true
  opt_uses:
  - schedule_run_command
  implements:
  - CHWVM
  - DFSS
  - ZTC

May I know whether you could enhance the tool to display the following extra table? By viewing the below example, I could easily know that I need to create a new type with the abstract type listed in the table.

ACTUAL FIELDS                             TYPE FIELDS                               ABSTRACT                                  
=======================================   =======================================   =======================================   
chilled_water_valve_percentage_command    chilled_water_valve_percentage_command    CHWVM                                   
chilled_water_valve_percentage_sensor     chilled_water_valve_percentage_sensor     CHWVM                                     
discharge_fan_run_command                 discharge_fan_run_command                 DFSS                                     
discharge_fan_run_status                  discharge_fan_run_status                  DFSS                                     
schedule_run_command                      schedule_run_command                      
zone_air_temperature_sensor               zone_air_temperature_sensor               ZTC                                     
zone_air_temperature_setpoint             zone_air_temperature_setpoint             ZTC

**Comment by tasodorff** [comment]
i will take a look next week and see if i can add it. A bit more complex than the regular type match, but there may be a way.

**Comment by mschulze17** [comment]
@tasodorff bump

**Comment by tasodorff** [comment]
this is fairly complex, and the new ontology explorer should cover most of the need for type matching.
