### ISSUE TITLE
Query about the existing standard point name for the "Remote/Local"

### ISSUE THREAD

**Issue by conroy-chee** [google/digitalbuildings#253]
We have been told that the Remote/Local is the important parameter to be stored in the cloud database e.g. firestore. I have tried to search the equivalent point name defined in the telemetry field list, but I could not get any name that matches to it. May I know whether there is an existing name that is pointing to this “Remote/Local” 

The value set for this “Remove/Local” SCADA point name is “Remote” and “Local”, and the definition of the value is shown as below:

Remote – The system is controlled remotely
Local – The system is controlled locally

**Comment by grafnu** [comment]
I don't think this is a digital-buildings question, it relates to UDMI bits... you should transfer this question over do either udmi-discuss@ or the github issues there (https://github.com/faucetsdn/udmi).

**Comment by mschulze17** [comment]
Solved
