### ISSUE TITLE
Instance_validator cannot return type if is_canonical: true is undefined

### ISSUE THREAD

**Issue by conroy-chee** [google/digitalbuildings#281]
The instance_validator cannot generate the type if is_canonical: true is undefined. How can let it generate type even though is_canonical is not present?

With is_canonical: true
![image](https://user-images.githubusercontent.com/80947411/124426566-cbdfa380-dd9c-11eb-98f9-11b7f2d60a9c.png)

Without is_canonical: true
![image](https://user-images.githubusercontent.com/80947411/124426698-faf61500-dd9c-11eb-982e-8b90587413a3.png)

**Comment by charbull** [comment]
@tasodorff will assign this one to you

**Comment by tasodorff** [comment]
There is no way except to declare the type canonical. This is intended behavior; we do not want to match instances of non-canonical types, and therefore any type that is not canonical will not get automatically matched.

**Comment by mschulze17** [comment]
Closed based on Trevor's comment above
