### ISSUE TITLE
Feature request: allow aliases for physical quantities

### ISSUE THREAD

**Issue by pisuke** [google/digitalbuildings#297]
**Describe the bug**
At the moment one unit is mapped only to one physical quantity name.
However there are many cases where a unit can measure physical quantities with different aliases.
For instance meters can measure length, height, level, etc.
There are also many adimensional quantities that would map to no_units (typically ratios and factors, like power factor or daylight factor).
I suggest to add the possibility to have "aliases" of quantities. 
For instance for "meter" the main quantity would be "length" and it can have "level", "height", "width" as aliases/synonyms.
Thanks!

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**OS (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by pisuke** [comment]
@charbull @tasodorff @berkoben this is now very urgent in projects needing especially adimensional units for measurements like currentratio as also noted in #298

**Comment by charbull** [comment]
@pisuke would like to propose a pull request for this bug?

**Comment by charbull** [comment]
@pisuke any chance you can submit a pull request for this feature? or you dont want to touch the code ? :)

**Comment by charbull** [comment]
@pisuke discussed internally needs brainstorming/discussion, please bring it up in our meeting on thursday for discussion

**Comment by pisuke** [comment]
@charbull sure, I thought we had agreed that adding the alias and relaxing the validator checks was the way forward, but let's discuss it again.

**Comment by charbull** [comment]
@pisuke is there an update on this?

**Comment by mschulze17** [comment]
@charbull - has this been solved?

**Comment by charbull** [comment]
yes this is resolved. I am closing it
