### ISSUE TITLE
Kill Validator After First Failure

### ISSUE THREAD

**Issue by tasodorff** [google/digitalbuildings#387]
The following is the result of the ontology validator.

```
Starting Yaml Validator!
Findings in fields/telemetry_fields.yaml
ERROR : Field "water_leak_sensor" is not a valid construction

Findings in SAFETY/entity_types/ABSTRACT.yaml
Traceback (most recent call last):
ERROR : Field name "water_leak_sensor" is undefined.
```

The second error is redundant and confusing. 

A few options:

1. Make the validator execute in an order and surface like errors together (e.g. evaluate all failed fields, if errors then surface them all then stop).
2. Kill the validation after the first error.

**Comment by mschulze17** [comment]
@tasodorff bump

**Comment by tasodorff** [comment]
we need to perform certain checks that have dependencies all at once (are all fields valid? if not, find all invalid fields then stop; dont give me all the subsequent errors that result from the fields not being valid -- those arent real issues).

**Comment by tasodorff** [comment]
in the backlog
