### ISSUE TITLE
Subfield suggestion flap for HVAC indoor DX units

### ISSUE THREAD

**Issue by gerrykou** [google/digitalbuildings#418]
Do you think worth including flap or another word , for HVAC indoor DX unit moving flaps, used to control airflow  - direction.
flap_mode(start / stop)

Instead damper can be used that is already in subfields, but dampers use to control airflow - volume etc and have position as control point.

**Comment by gerrykou** [comment]
@tasodorff I was talking about the blades that are responsible for the up/down swing in split units 
https://www.fujitsu-general.com/shared/g-eu/img-0000-split-floor-double-auto-swing-01.png

**Comment by tasodorff** [comment]
Oh interesting. What modes do these blades operate in? Is there another document you can link me that describes the behavior? I think I would be okay with `blade` but I want to think about it in the context of a specific device.

**Comment by mschulze17** [comment]
@tasodorff ping

**Comment by tasodorff** [comment]
@gerrykou I think either `louver` or `blade` would be appropriate; since `louver` seems more specific, I think that is what we should go with (`blade` could refer to any sharp edge, and it might be too confusing to add a specific definition to it). 

Please proceed with `louver`.
