### ISSUE TITLE
TPKD Point name inclusive query

### ISSUE THREAD

**Issue by Terry-Ter** [google/digitalbuildings#435]
Hi, we were discussing the mandatory points for digital building ontology. We would like to seek your opinion about the necessity of point for a certain type of device. This would greatly reduce the time in creating new type. Thank you.

**Pump**

Please help to verify whether the following is necessary:
	Reset Alarm
	SIMULATION ON
	OFF_AL
	ON_AL
	RUN_TIME
	Moto_power
	Moto_voltage
	Moto_current
	Moto_torque
	Moto_rpm
	Moto_heat_load
	Vfd_dc_voltage
	Brake_dynamo_sec
	Brake_dynamo_2min
	Cooling_fin_temperature
	Inverter_heat_load
	Inverter_rated_current
	Inverter_maximum_current
	Si_control_status
	Control_card_overheating

![image](https://user-images.githubusercontent.com/80947411/145133368-0a386f9d-1673-42f0-a2b0-ae50b7fef30f.png)

![image](https://user-images.githubusercontent.com/80947411/145133499-27fa26e3-e575-4e35-8f2d-c747c2b3ff78.png)

**Chiller**
Please help to verify whether the following is necessary:
	NO1 Compresser Communication Alarm
	NO2 Compresser Communication Alarm
	Gateway Communication Alarm
	Phase failure protection Trip Alarm
	SIEMENS POL Controller Trip Alarm

![image](https://user-images.githubusercontent.com/80947411/145135840-950a9dd0-9813-43b4-9d69-91faafedc784.png)

**Comment by conroy-chee** [comment]
hi @tasodorff , could you help to review this question? Thank you.

**Comment by tasodorff** [comment]
Of those fields listed, here is what i would bring in:

 Reset Alarm *NOT NEEDED*
 SIMULATION ON *NOT NEEDED*
 OFF_AL *NOT NEEDED*
 ON_AL *NOT NEEDED*
 RUN_TIME *NOT NEEDED*
 Moto_power compressor_power_sensor
 Moto_voltage *NOT NEEDED*
 Moto_current *compressor_current_sensor*
 Moto_torque *NOT NEEDED*
 Moto_rpm *NOT NEEDED*
 Moto_heat_load *compressor_thermal_cooling_sensor*
 Vfd_dc_voltage *NOT NEEDED*
 Brake_dynamo_sec *NOT NEEDED*
 Brake_dynamo_2min *NOT NEEDED*
 Cooling_fin_temperature *NOT NEEDED*
 Inverter_heat_load *NOT NEEDED*
 Inverter_rated_current *NOT NEEDED*
 Inverter_maximum_current *NOT NEEDED*
 Si_control_status *NOT NEEDED*
 Control_card_overheating *NOT NEEDED*

**Comment by tasodorff** [comment]
@Terry-Ter does this answer your question?

**Comment by Terry-Ter** [comment]
HI Trevor, yes it answered the question and the points that are not needed are removed
