### ISSUE TITLE
Project has a very ambitious name!

### ISSUE THREAD

**Issue by aidan-parkinson** [google/digitalbuildings#45]
This is great work. Good to see

However, the word "Ontology" to my understanding implies a high level of validity (to me at least). An example of which might be "energetics" and "quantum mechanics" as two fundamentally different types of observation.

Isn't this really another "Social Construct" representing quite a contextually dependent system of significant inherent bias? Why was the term "Model" not used for this project, as potentially a more valid and widely used term?

From my perspective there is a danger that the name of this project is over-selling its possible applications. Sorry to be a headache!

**Comment by aidan-parkinson** [comment]
As a crude instance of the point, this "Ontology" might not be human understandable if you only speak French.

**Comment by charbull** [comment]
Hello @aidan-parkinson,

Thank you for dropping by,

The word Ontology is being used recently with the semantic web standards (OWL, RDF).
Various `Ontologies` exist in this domain to represent building/hvac information such as Brick, BOT, and others.
Our work here extends and builds on top of these previous ontologies.

Can you please use send your questions to this discussion list: google-digital-building-discuss@googlegroups.com

Thank you
Charbel

**Comment by aidan-parkinson** [comment]
Okay, I'm about to get more critical - because I think this is an issue, not a question. I don't understand why this has been closed without answering the question?

I understand the project used OWL. I am not sure that immediately means that a meaningful Ontology has been created. There's a number of examples of unexplained jargon here. For example, how does this project describe what "Building Static Pressure" means (are things getting hotter)? What is a "setpoint" (am I about to achieve something in a tennis match)? Jargon is often discussed in this project, but not defined in an organised way. A meaningful Ontology needs to carefully describe domain specific terms used (perhaps with multiple understandable examples). Has this been peer-reviewed?

As a "model" this project wouldn't be open to such criticism and I think the term us a better fit at the moment.
