### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by david-waterworth** [google/digitalbuildings#46]
I'm watching this project with interest as it's aligned with my research topic (ML and built environment).

Do you intend on adding some examples? I think that would really help, i.e. a minimal yaml example and perhaps a tutorial on how to validate and generate a DRF. Also, it's not really clear to me what I'd do with the RDF, some notes on the application of RDF would be useful. 

And do you intend adding some sort of mapping between the representation and the source data - i.e. the main use I have for any building representation is to enable me to query the BMS data I require for my models. So for each sensor I would want to include a field which would contain some sort of query string which would allow me to access a data lake the histories data was stored in, or perhaps the bacnet id's to directly query the BMS. I'm not 100% but neither Haystack or BrickSchema seem to address this other than having say a `cur` and `hist` tag.

Finally it's not really clear what the ibr project is all about. The readme implies it's a file format "that can be adapted to multiple use cases " but the example shows a building floorplan. It's not really clear how you'd adapt it to other use cases.

**Comment by charbull** [comment]
Hi @david-waterworth, 

Thank you for dropping by, 

Can you please use send your questions to this discussion list: google-digital-building-discuss@googlegroups.com

Thank you
Charbel
