### ISSUE TITLE
Ontology is full of jargon

### ISSUE THREAD

**Issue by aidan-parkinson** [google/digitalbuildings#48]
Okay, I'm about to get more critical - because I think this is an issue, not a question. I don't understand why this has been closed without answering the question?

I understand the project used OWL. I am not sure that immediately means that a meaningful Ontology has been created. There's a number of examples of unexplained jargon here. For example, how does this project describe what "Building Static Pressure" means (are things getting hotter)? What is a "setpoint" (am I about to achieve something in a tennis match)? Jargon is often discussed in this project, but not defined in an organised way. A meaningful Ontology needs to carefully describe domain specific terms used (perhaps with multiple understandable examples). Has this been peer-reviewed?

As a "model" this project wouldn't be open to such criticism and I think the term is a better fit at the moment.

_Originally posted by @aidan-parkinson in https://github.com/google/digitalbuildings/issues/45#issuecomment-659729744_

**Comment by tasodorff** [comment]
The ontology defines all those concepts, and makes inferences about their qualities. For example, `setpoint` is defined in the subfields documents as "Control target of process or system."; static pressure sensors are defined as combinations of these concepts:

> static: "Resting or stagnant value (e.g. static_pressure_sensor)."

> pressure: "Measured force per unit area within a system or process."

> sensor: "Component used to measure some quality of a system or process. Can be feedback for an analog command."

There is no doubt that the ontology is filled with jargon, but that jargon is not without definition. Terms are also namespaced to maintain domain specificity. If you have any questions or comments regarding specific constructions in the ontology, please post them.
