### ISSUE TITLE
Add a new point name for the "supply fan VFD/bypass status"

### ISSUE THREAD

**Issue by RathishKJ** [google/digitalbuildings#486]
Hello,

For supply fan VFD/bypass status as point descriptor, in AHU, there is no existing data point available in the Github.
New data point has to be created which is **supply_fan_bypass_status**
This is created using the existing sub fields as below

    Descriptor: Supply
    component: Fan
    Measurement: Frequency
    Point Type: Status
    Please validate this and add this in the github.

regards,
Rathish

**Comment by mschulze17** [comment]
@tasodorff - PTAL and advise on action

**Comment by tasodorff** [comment]
Hi @RathishKJ , this can be done by extending the ontology in a PR. Please submit a pull request and we will merge this.
