### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by david-waterworth** [google/digitalbuildings#50]
I'm in the middle of a literature review on the current state of building ontologies. I believe `digitalbuildings` warrants inclusion. Do you have any publication, if not it would be nice if you added a citation section to the readme?

Creating a DOI would be nice as well - https://github.blog/2014-05-14-improving-github-for-science/

**Comment by charbull** [comment]
Hi @david-waterworth it is in the pipe ... for now feel free to cite the repo.
