### ISSUE TITLE
request for addition of asset abbreviation in the BDNS

### ISSUE THREAD

**Issue by RathishKJ** [google/digitalbuildings#500]
Hello,

There are equipment that are not abbreviated in the BDNS. We are proposing the abbreviations also along with the asset name. Please provide inputs or concurrence to proceed to initiate the pull request for the same.

1.Ceiling Suspended unit--> CSU
2.Exhaust Dry Scrubber Unit--> DSU
3.Air Purifier Unit--> APU
4.Air Washer Unit--> AWSH
5.Vaporizer Panel - Gas temperature is monitored through BOS (hard integration)--> VP
6.Hydrogen Sensor--> HDS
7.Velocity sensor--> VS

Regards,
Rathish KJ

**Comment by charbull** [comment]
@tasodorff @mschulze17 ptal

**Comment by tasodorff** [comment]
@RathishKJ the BDNS is maintained separately; if you wish to extend it, please make your requests in an issue there: https://github.com/theodi/BDNS/issues

If you wish to add these to the Digital Buildings Ontology (this repository) you will need to provide information regarding what these units are, and how to distinguish them from one another. 

For example, a CSU sounds an awful lot like a FCU. If the difference between a CSU and an FCU is that CSU is ceiling mounted and FCU is only sometimes ceiling mounted we will not accept CSU as a new concept. We don't care about where it is mounted; its inconsequential to its function. For this reason you will see many BDNS concepts (such as RTU, ACU, and CRAC) have no representation in DBO -- they are trivially different from other, well defined concepts. All concepts must have a definition that gives other users clear guidance on what that particular device is and how it is *meaningfully* distinct from other devices.
