### ISSUE TITLE
Ontology Explorer Updates

### ISSUE THREAD

**Issue by tasodorff** [google/digitalbuildings#537]
Some ideas for ontology explorer enhancements, to aid in the workflow: 
1. Allow the ontology to be rebuilt without closing the app.
2. Reduce the number of inputs needed to do type comparison (all the little pop-up options should be refactored).

**Comment by charbull** [comment]
could we bring this internally and close this out?
@mschulze17 fyi

**Comment by charbull** [comment]
@tasodorff @trav3711 @mschulze17 can this be closed?

**Comment by trav3711** [comment]
I think so?

**Comment by mschulze17** [comment]
brought into the backlog, closing item. thanks @trav3711
