### ISSUE TITLE
Validator Tool is issue 

### ISSUE THREAD

**Issue by dheeju143** [google/digitalbuildings#547]
Hi i have noticed that validator Tool having some issue. below i have got the errors kindly help me out what is the way to troubleshoot

`python3 toolkit.py -i /home/google/digitalbuildings/tools/automation/YAMLFILES/KEF.yaml --generate
`

> Traceback (most recent call last):
  File "/home/dheeraj/validator/digitalbuildings/tools/toolkit.py", line 27, in <module>
    from validate import handler
  File "/usr/local/lib/python3.9/dist-packages/instance_validator-0.0.1-py3.9.egg/validate/handler.py", line 26, in <module>
    from validate import subscriber
  File "/usr/local/lib/python3.9/dist-packages/instance_validator-0.0.1-py3.9.egg/validate/subscriber.py", line 22, in <module>
    from google.auth import jwt
ModuleNotFoundError: No module named 'google.auth'

@tom-skoczylas

**Comment by trav3711** [comment]
Hi @dheeju143, are you using a Windows operating system?

**Comment by dheeju143** [comment]
Hi @trav3711 Thanks for reply,

Am using Windows 11 Pro and python version 3.10.1. Yes I have successfully run the global_setup.bat 

Attached the screenshots for reference issue below.

![sc1](https://user-images.githubusercontent.com/86141162/164515162-52401ea3-92ed-44de-b242-d9dacd7f56d3.png)
![sc2](https://user-images.githubusercontent.com/86141162/164515172-2b587ad1-c5a2-417d-b91d-b92d550e069b.png)
![sc3-error](https://user-images.githubusercontent.com/86141162/164515179-128015b2-3242-49ca-ab4e-da101afaee43.png)

**Comment by trav3711** [comment]
Hi @dheeju143 I apologize for the delay. I am having trouble replicating your error, so there are two bits of advice I can offer that might get you out of this.

The first is to downgrade your Python version or ensure that you're running with Python 3.7.7. This is the latest LTS Python version that we know works with our setup script. Another solution is to run out tooling on a linux machine if you have access to one.

We will keep looking into this bug and update you on any progress.

**Comment by dheeju143** [comment]
@trav3711  I have updated 3.10.1 to PY- 3.10.4 and works fine on Windows 11 pro. 

Thank you very much. @trav3711
