### ISSUE TITLE
Deserialization fails if a lone entity's key includes a space character

### ISSUE THREAD

**Issue by ahemphill** [google/digitalbuildings#551]
**Describe the bug**
If a .yaml configuration file contains a lone entity whose key does not include a space character, `validator.handler.Deserialize()` returns a single-entry dictionary as expected. If an entity with the same attributes is keyed under a value which includes a space character, however, the method returns an empty dictionary.

**To Reproduce**
1. Save the following as `no_space.yaml`:
```
AHU-1:
  cloud_device_id: 2800458382553943
  type: HVAC/AHU_FAN_US_SVL_MP2_1
  guid: 5a8ab907-e9fe-480d-b301-77db1f9808ea
```
2. Run `validate.handler.Deserialize(['no_space.yaml'])`
3. Observe that it returns:
```
({'5a8ab907-e9fe-480d-b301-77db1f9808ea': <validate.entity_instance.EntityInstance object at 0x7f8af0571310>}, <ConfigMode.INITIALIZE: 'INITIALIZE'>)
```
4. Save the following as `space.yaml`:
```
AHU 1:
  cloud_device_id: 2800458382553943
  type: HVAC/AHU_FAN_US_SVL_MP2_1
  guid: 5a8ab907-e9fe-480d-b301-77db1f9808ea
```
5. Run `validate.handler.Deserialize(['space.yaml'])`
6. Observe that it returns: 
```
({}, <ConfigMode.INITIALIZE: 'INITIALIZE'>)
```
7. Add to `space.yaml` an arbitrary entity whose key does not include a space character and observe that `validate.handler.Deserialize(['space.yaml'])` returns as expected.

**Expected behavior**
I expect `validate.handler.Deserialize()` to return a non-empty dictionary when it receives a configuration file containing a lone entity keyed under a value which includes a space character.

**OS (please complete the following information):**
macOS 12.2.1; Python 3.7.9

**Additional context**
Space characters occur in real building data and being able to test the associated entities in isolation is important for the `scoring` tool.

**Comment by ahemphill** [comment]
The deserializer also appears to dislike slash (`/`) characters.

**Comment by trav3711** [comment]
Both of bug fixes have been merged.

**Comment by ahemphill** [comment]
Thank you!
