### ISSUE TITLE
Learning material not accessible

### ISSUE THREAD

**Issue by edgsousa** [google/digitalbuildings#556]
The learning modules links on README are not accessible.

**Comment by tasodorff** [comment]
@edgsousa thanks for pointing this out. we are looking at alternatives to the slide deck, since it seems we cannot share those publicly outside Google. I will close this issue when we have converted the documents over to a format that you should be able to view.

**Comment by charbull** [comment]
Thx for letting us know, we are working around it.
Thank you

**Comment by charbull** [comment]
@edgsousa issue resolved, please take a look.
