### ISSUE TITLE
How to manage speed mode

### ISSUE THREAD

**Issue by ghairapetian** [google/digitalbuildings#589]
Hello, 

I have a warm air curtain with 6 differents speed mode (0, 20, 40, 60, 80, 100)%

The telemetry field discharge_fan_speed_mode mention the following : 
  - AUTO
  - LOW
  - MEDIUM
  - HIGH
  - OFF
  - VFD

that does not correspond to my needs. However, in my case, it's a fan on discharge side, and it runs with speed mode. So I can't really create a new telemtry with a new name.

How can i resolve this issue ?

Thank you very much,

Have a nice day,

**Comment by charbull** [comment]
@tasodorff any updates on this one?
@mschulze17 fyi

**Comment by ghairapetian** [comment]
Hello, this issue still block the Warm air curtain modelisation on 50A project. Any updates ?

**Comment by charbull** [comment]
@tasodorff ping :)

**Comment by tasodorff** [comment]
hi @ghairapetian 

we have been exploring the best option here and I need more info on the field itself: will it be sending state data (e.g. states of 20, 40, 60, 80, 100) or will can it send those discrete values as part of a message with units of percent?

```
speed_field:
  present_value: points.speed.present-value
  units:
    key: pointset.points.speed.units
    values:
      percent: percent
```

If it can be made to send the data with units but which only sends discrete values of 20, 40, 60, 80, and 100 then the existing `discharge_fan_speed_percentage_command` field will work fine. If not, we would need to add states specifically to handle the 20, 40, 60, etc. states; this would not be ideal and we would need to determine what best to call them. Can you please let me know if the field can support units?

**Comment by ghairapetian** [comment]
Hello,
the field does not support units and takes the values (0,1,2,3,4,5).
Those values mean : 
OFF
Speed 1
Speed 2
Speed 3
Speed 4
Speed 5

**Comment by tasodorff** [comment]
ah well this makes it easier. what we could do is something like this:
`OFF`:`OFF`
`Speed 1`:`VERY_LOW`,
`Speed 2`:`LOW`,
`Speed 3`:`MED`,
`Speed 4`:`HIGH`,
`Speed 5`:`VERY_HIGH`

We don't have strict definitions around what speed percentages mean, so we are free to define `VERY_LOW` and `VERY_HIGH` relatively (e.g. `VERY_LOW` as lower speed relative to `LOW`).

It is also acceptable to have a mapping like this for exact speed.

`OFF`:`OFF`,
`Speed 1`:`20_PERCENT`,
`Speed 2`:`40_PERCENT`,
`Speed 3`:`60_PERCENT`,
`Speed 4`:`80_PERCENT`,
`Speed 5`:`100_PERCENT`

Either is acceptable for now.

**Comment by ghairapetian** [comment]
Hello, thank you for your answer.

The field discharge_fan_speed_mode is already defined into DBO with different values (not OFF and 5 speed mode) :
  - AUTO
  - LOW
  - MEDIUM
  - HIGH
  - OFF
  - VFD

how can we manage that ? To we need to change the field name ?

**Comment by tasodorff** [comment]
Just add the states you need to `states.yaml` and list them on the `discharge_fan_speed_mode`.

**Comment by ghairapetian** [comment]
Hello, 

It works !

I did not understand that that I could use only a few of states listed in discharge_fan_speed_mode and not all of them.

Thank you very much,

I wish you a nice day,

Grégory
