### ISSUE TITLE
How to set _config_mode

### ISSUE THREAD

**Issue by prajgujarathi** [google/digitalbuildings#594]
**Describe the bug**
I keep getting errors on valid YMAL files saying KeyError: 'No valid _config_mode is set' when trying to validate using instance_validator

**To Reproduce**
Go to folder digitalbuildings\tools\
try validating the file using the validator using the command py .\toolkit.py --input file-path -v

**Expected behavior**
It errors out with error:
-py3.9.egg\validate\instance_parser.py", line 374, in _ValidateEntityContent
    raise KeyError('No valid _config_mode is set')
KeyError: 'No valid _config_mode is set'

**OS (please complete the following information):**
windows

Here are the file contents:

CONFIG_METADATA:
  operation: EXPORT

US-MTV-1804:
  type: FACILITIES/BUILDING 
  id: FACILITIES/ 

device2715203:
  type: HVAC/FAN_SS_DSP
  cloud_device_id: 2550389110353931
  translation:
    exhaust_fan_run_command:
      present_value: "points.efss_1.present_value"
      states:
        ON: "true"
        OFF: "false"
    schedule_run_command:
      present_value: "points.schedule_1.present_value"
      states:
        ON: "true"
        OFF: "false"
    zone_air_cooling_temperature_setpoint:
      present_value: "points.eff_clg_sp_1.present_value"
      units:
        key: "pointset.points.eff_clg_sp_1.units"
        values:
          degrees_fahrenheit: "°F"
    unoccupied_zone_temperature_cooling_setpoint:
      present_value: "points.unocc_clg_sp_1.present_value"
      units:
        key: "pointset.points.unocc_clg_sp_1.units"
        values:
          degrees_fahrenheit: "°F"
    zone_air_unoccupied_heating_temperature_setpoint:
      present_value: "points.unocc_htg_sp_1.present_value"
      units:
        key: "pointset.points.unocc_htg_sp_1.units"
        values:
          degrees_fahrenheit: "°F"
    failed_alarm:
      present_value: "points.ef_fail_1.present_value"
      states:
        ON: "true"
        OFF: "false"
    zone_air_heating_temperature_setpoint:
      present_value: "points.eff_htg_sp_1.present_value"
      units:
        key: "pointset.points.eff_htg_sp_1.units"
        values:
          degrees_fahrenheit: "°F"
    occupied_zone_temperature_cooling_setpoint:
      present_value: "points.occ_clg_sp_1.present_value"
      units:
        key: "pointset.points.occ_clg_sp_1.units"
        values:
          degrees_fahrenheit: "°F"
    zone_air_occupied_heating_temperature_setpoint:
      present_value: "points.occ_htg_sp_1.present_value"
      units:
        key: "pointset.points.occ_htg_sp_1.units"
        values:
          degrees_fahrenheit: "°F"
    exhaust_fan_run_status:
      present_value: "points.efst_1.present_value"
      states:
        ON: "true"
        OFF: "false"
    zone_air_temperature_sensor:
      present_value: "points.zone_temp_asvi_1.present_value"
      units:
        key: "pointset.points.zone_temp_asvi_1.units"
        values:
          degrees_fahrenheit: "°F"
  connections:
    US-MTV-1804: CONTAINS

**Comment by charbull** [comment]
Can you please start with an example from here:
https://github.com/google/digitalbuildings/tree/master/tools%2Fvalidators%2Finstance_validator%2Ftests%2Ffake_instances%2FGOOD

**Comment by trav3711** [comment]
@charbull Isn't the config_metadata block necessary? @prajgujarathi try validating with:

```
CONFIG_METADATA:
operation: INITIALIZE
```

**Comment by prajgujarathi** [comment]
Yes, it did. Thank you.

**Comment by trav3711** [comment]
Great. Closing issue.

**Comment by charbull** [comment]
fyi: the initialize is the default setup, it is not required.
