### ISSUE TITLE
Website links broken

### ISSUE THREAD

**Issue by rektide** [google/digitalbuildings#626]
**Describe the bug**
Many links on website are broken.

**To Reproduce**

One example:
* Go to https://google.github.io/digitalbuildings/ontology/yaml/
* Click the link to the model (points to https://google.github.io/ontology/docs/model.md )

**Expected behavior**
Yaml model shows up

Actual expected destination might be: https://google.github.io/digitalbuildings/ontology/docs/model

**Comment by charbull** [comment]
@rektide fixed thank you for reporting it.
