### ISSUE TITLE
Chilled

### ISSUE THREAD

**Issue by aidan-parkinson** [google/digitalbuildings#66]
I don't think `chilled` water is pure `H2O`. Chilled water is a `solution`.

There's a lot to do here.

**Comment by tasodorff** [comment]
what is there to do? what is your suggestion?

**Comment by aidan-parkinson** [comment]
I'm afraid I am getting tired of this. I have been making very clear indications of genuine issues and suggested improvements to this ontology that are being rejected on the basis of an evidently narrower base of support. I am not getting paid by Google to contribute to this project. I care about this subject matter and the success of the industry, but if this project is being maintained with the attitude displayed here then there is little point in me contributing at all. I can easily make the competition, thank you.

**Comment by aidan-parkinson** [comment]
What I mean is that the solutions that are being rejected have a broader and deeper basis for support than the ones that are being retained. This makes no sense in maintaining an Ontology.

**Comment by tasodorff** [comment]
If your suggestion is to narrow `water` to pure substance (i.e. not mixtures) and use `solution` for glycol or other fluid mixtures (e.g. `chilled_water`, `chilled_glycol`, or `chilled_solution`), then please say so; if you are saying that water should always be modified by solution (e.g. `chilled_water_solution`) then please say so. If you are asserting that water -- unless truly 'pure' water -- should always be classified as solution then please say so. I would tend to agree with the first, want to consider more closely the second, and tend to reject the third.

The feedback you have given thus far is vaguely critical, and not framed in a way that suggests what _specifically_ could be done to improve the ontology. I neither agree nor disagree with your original comment; I simply don't understand what your suggestion is for modifying the existing ontology. Please clarify.
