### ISSUE TITLE
Pull request #656 merge 

### ISSUE THREAD

**Issue by Karthi8883** [google/digitalbuildings#756]
The below Canonical type has id field missing, needs to be added.

https://github.com/google/digitalbuildings/blob/e2169b56e28c748208087c825a61464664afe54a/ontology/yaml/resources/HVAC/entity_types/VAV.yaml#L42

**Comment by charbull** [comment]
@cstirdivant can you help on this please?

**Comment by cstirdivant** [comment]
This issue has been reoslved with the merging of PR #767
