### ISSUE TITLE
Cleanup inconsistency in Module 1: Lesson 4 - Field Enumeration Example 

### ISSUE THREAD

**Issue by connorjcantrell** [google/digitalbuildings#758]
Issue:
Located in [Module 1: Lesson 4](https://github.com/google/digitalbuildings/blob/master/ontology/docs/learning/Module%201%2C%20Lesson%204_%20Fields%20(v1_git).pdf) page 18, according to lesson, two identical sensors are distinguished by `<field>_#`, however the field enumeration example is missing an underscore.  

Solution:
The field example should be changed from `supply_air_static_pressure_sensor1` to `supply_air_static_pressure_sensor_1`.

**Comment by mschulze17** [comment]
Thank you for flagging this - this feedback has been passed along to the team responsible for making edits to content. I'll leave this Issue open until the updates get uploaded to Github.

**Comment by charbull** [comment]
@connorjcantrell the learning modules are updated, please take a look.

**Comment by mschulze17** [comment]
@connorjcantrell the learning modules are updated, please take a look
