### ISSUE TITLE
[Telemetry Validation Run on Windows]

### ISSUE THREAD

**Issue by darshanjain12** [google/digitalbuildings#789]
Telemetry validation ending with : Top-level exception occurred in callback while processing a message , AttributeError: 'TelemetryReportPoint' object has no attribute 'GetPrintableMessage'
PubSub subscription failed with error: 'TelemetryReportPoint' object has no attribute 'GetPrintableMessage'

![image](https://user-images.githubusercontent.com/104188629/193655256-981805a4-b666-4544-944e-7b3a7122bef5.png)

**Comment by charbull** [comment]
@darshanjain12 thanks for reporting, @trav3711 is taking a look and will update here soon.

**Comment by charbull** [comment]
@darshanjain12 ping, closing for now please feel free to re-open if needed.
