### ISSUE TITLE
[VALIDATOR BROKEN AFTER RECENT UNIT UPDATE]

### ISSUE THREAD

**Issue by darshanjain12** [google/digitalbuildings#837]
The Validator has been broken and we are not able to run the ontology validator please check. Attaching the snapshots.

![image](https://user-images.githubusercontent.com/104188629/201515836-1fc68271-9401-417e-bdf2-23f6996a2759.png)

Please do the needful

**Comment by tasodorff** [comment]
can you please sync with the master? 

once you have done that, rerun. if you still get the error, please share the copy of the units.yaml file you are using

**Comment by darshanjain12** [comment]
Yes synced with the master.
Please find the link for used units file: https://drive.google.com/file/d/1gPvDdP-nRDwfX4azZQLVFYMNyYAjSTMR/view?usp=sharing

**Comment by tasodorff** [comment]
@darshanjain12 that unit file looks correct; have you reinstalled the validator after the most recent update?

You can run `pip_install.bat` in the `tools` directory (if you are running windows). Or, if you still are getting the error, try opening a pull request which will run the validator in the cloud; if the error occurs there, then we will be able to see the logs and troubleshoot further.

**Comment by darshanjain12** [comment]
@tasodorff  I have run the pip_install.bat again but still facing the same error. Opening a pull request for the same as suggested by you

**Comment by tasodorff** [comment]
@darshanjain12 i see the validator has passed in github, so this appears to be a local issue on your machine. perhaps we set up a call to walk through the config on your local machine.

**Comment by darshanjain12** [comment]
Hi Trevor,

Yes it seems like some issue at local windows machine only, recently tried it on my other Linux machine it is working well on that machine. But I am not getting exactly where the problem is in that machine.

**Comment by tasodorff** [comment]
if youd like to schedule some time, please email me directly and we can set some time. its clearly an install issue, but i dont know where the problem would be yet.

**Comment by darshanjain12** [comment]
Definitely that would really be helpful

**Comment by charbull** [comment]
closing this for now. Feel free to reopen.
