### ISSUE TITLE
Ensure quality of exception handling for instance validator

### ISSUE THREAD

**Issue by Ray725** [google/digitalbuildings#84]

**Comment by Ray725** [comment]
@berkoben

**Comment by charbull** [comment]
@Ray725 can you please ad a description

**Comment by Ray725** [comment]
Approve the design pattern of exception handling as seen here: https://github.com/google/digitalbuildings/blob/master/tools/validators/instance_validator/instance_parser.py#L83. For this project, any error we see means it's unreasonable to continue running the parser, and thus we immediately throw the error.

**Comment by mschulze17** [comment]
Closed per review with Trevor
