### ISSUE TITLE
[FACING ISSUE WITH VALIDATOR ON LINUX MACHINE]

### ISSUE THREAD

**Issue by darshanjain12** [google/digitalbuildings#841]
Faced issue while running validator.
The validator was working fine but abruptly started giving this error.
Please help with the same.

Top-level exception occurred in callback while processing a message
Traceback (most recent call last):
  File "/home/DBO/digitalbuildings/tools/tooling/lib/python3.10/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 126, in _wrap_callback_errors
    callback(message)
  File "/home/DBO/digitalbuildings/tools/tooling/lib/python3.10/site-packages/validate/telemetry_validator.py", line 125, in ValidateMessage
    tele = telemetry.Telemetry(message)
  File "/home/DBO/digitalbuildings/tools/tooling/lib/python3.10/site-packages/validate/telemetry.py", line 58, in __init__
    self._parse_data(message.data))
  File "/home/DBO/digitalbuildings/tools/tooling/lib/python3.10/site-packages/validate/telemetry.py", line 135, in _parse_data
    p = point.Point(point_name, value.get(PRESENT_VALUE))
AttributeError: 'str' object has no attribute 'get'

Thanks & Regards,
Darshan Jain

**Comment by darshanjain12** [comment]
Particularly this error "Pub Sub subscription failed with error: 'str' object has no attribute 'get'

**Comment by trav3711** [comment]
Hi @darshanjain12 can you provide the command you used that gave you this error?

**Comment by tasodorff** [comment]
@darshanjain12 as discussed today, please look at the payload being sent prior to this error arising (it should print to console). the error appears to be a malformed payload, where the validator is expecting a key:value pair, but is instead getting a lone string. please rerun and ensure the payload looks correct.

if you are still having trouble, please paste the payload into this thread and we can take a look.

**Comment by darshanjain12** [comment]
Not getting the exact payload thread getting the error in middle of telemetry validation.
 Please suggest. Attached the screenshot

![Screenshot from 2022-11-23 19-50-11](https://user-images.githubusercontent.com/104188629/203570398-e8633896-9c1a-4c06-a1ae-dd408c70a19e.png)

**Comment by trav3711** [comment]
@darshanjain12 Could you please provide the command you are running that causes this error? I would like to duplicate the error with the same project and subscription.

**Comment by darshanjain12** [comment]
Thank you for guiding me through the process. 
Found out that one of the device was actually passing timestamp in place of present value.
