### ISSUE TITLE
GUID GENERATOR GIVING ERROR FOR PULLREQUEST

### ISSUE THREAD

**Issue by darshanjain12** [google/digitalbuildings#870]
Getting the error for Guid Generator that has been running on new pull request.

https://github.com/google/digitalbuildings/pull/869 Link to the pull request

**Comment by charbull** [comment]
@darshanjain12 please take a look, updated the main

**Comment by darshanjain12** [comment]
Yes. 
It has cleared all the checks.
Thank You
