### ISSUE TITLE
demo yaml files for tutorial are empty

### ISSUE THREAD

**Issue by capsulecorplab** [google/digitalbuildings#876]
**Describe the bug**
demo yaml files for tutorial in [./ontology/docs/learning/practice](https://github.com/google/digitalbuildings/tree/master/ontology/docs/learning/practice) are all empty 

**To Reproduce**
1. Go to [./ontology/docs/learning/practice](https://github.com/google/digitalbuildings/tree/master/ontology/docs/learning/practice)
2. Open any yaml file
3. See that they're empty

**Expected behavior**
They should have data that can be used against the instance validator as per [Module_2_Lesson_7_Validate_the_instance_and_telemetry.pdf](https://github.com/google/digitalbuildings/blob/master/ontology/docs/learning/Module_2_Lesson_7_Validate_the_instance_and_telemetry.pdf)

**Comment by charbull** [comment]
Thank you for opening the issue @capsulecorplab
@tasodorff please take a look.

**Comment by tasodorff** [comment]
will be fixed with https://github.com/google/digitalbuildings/pull/877

**Comment by charbull** [comment]
@capsulecorplab FYI, this is now fixed. Thank you for reporting it.
