### ISSUE TITLE
Add spell checker to description fields for ease of review.

### ISSUE THREAD

**Issue by tasodorff** [google/digitalbuildings#894]
Implement a spell checker which can scan `description` attributes for words that might be misspelled. 

We are seeing some misspellings passing review and could benefit from a Python spell checker to help warn the user during ontology validation. An example [here](https://pyspellchecker.readthedocs.io/en/latest/).

**Comment by trav3711** [comment]
+ 1

**Comment by charbull** [comment]
+1 this could be a github action.
@azenla do you want to have some github actions fun ? :)

**Comment by azenla** [comment]
> +1 this could be a github action.
> @azenla do you want to have some github actions fun ? :)

Sure! I can do that :)
