### ISSUE TITLE
INSTACE-VALIDATOR-ISSUE

### ISSUE THREAD

**Issue by darshanjain12** [google/digitalbuildings#915]
Dear Team,

Recent updated the repository and tried running instance validator facing one error please help.

![Uploading Screenshot from 2023-02-21 14-17-17.png…]()

**Comment by trav3711** [comment]
Hi Darshan,

I can't seem to open your screen shot. Can you post it again copy and paste the error you're facing along with the command you're running?

**Comment by darshanjain12** [comment]
Hi @trav3711  

error:

Traceback (most recent call last):
  File "/home/secutech/DBO/digitalbuildings-20-11-2022/digitalbuildings/tools/toolkit.py", line 26, in <module>
    from guid_generator.instance import generator

Command:
python3 toolkit.py -i /home/secutech/DBO/telemetry-validated-08-12-2022/SEISMIC-SENSOR/sss.yaml -v

**Comment by trav3711** [comment]
Hi @darshanjain12 Is that the full error message?

**Comment by darshanjain12** [comment]
Hi @trav3711 Yes it is full error message.

**Comment by trav3711** [comment]
Hi @darshanjain12 there is a PR out to patch this bug: #918 

hopefully will be merged by end of week.

**Comment by trav3711** [comment]
Hi @darshanjain12 this has been fixed. Happy validating.
