### ISSUE TITLE
Error in validation report generation

### ISSUE THREAD

**Issue by ghairapetian** [google/digitalbuildings#921]
**IMPORTANT**
DO NOT INCLUDE ANY PROJECT-SPECIFIC INFORMATION IN THIS TICKET!
ANY PROJECT-SPECIFIC CONTEXT (E.G. BUILDING CONFIG INPUTS) SHOULD BE
EMAILED DIRECTLY TO: digitalbuildings-support@googlegroups.com

PLEASE REFERENCE THIS ISSUE LINK IN YOUR EMAIL TO THAT GROUP

**Describe the bug**
The toolkit tool generate a partial validation report because of an error

**To Reproduce**
1. Go to '/digitalbuildings/tools'
2. Launch python3.9 toolkit.py -i my-dbo.yaml --udmi -v -s mySubscription -r ~/reportGCP -t 10
```
[INFO]  Starting validation process.
/home/ghairapetian/.local/lib/python3.9/site-packages/google/auth/_default.py:83: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/ghairapetian/.local/lib/python3.9/site-packages/validate/telemetry_validator.py", line 94, in <lambda>
    self._timer = threading.Timer(self.timeout, lambda: self.callback(self))
  File "/home/ghairapetian/.local/lib/python3.9/site-packages/validate/handler.py", line 258, in _TelemetryValidationCallback
    validation_report_dict = validation_report.GenerateReport()
  File "/home/ghairapetian/.local/lib/python3.9/site-packages/validate/telemetry_validation_report.py", line 110, in GenerateReport
    ERROR_DEVICES: [
  File "/home/ghairapetian/.local/lib/python3.9/site-packages/validate/telemetry_validation_report.py", line 111, in <listcomp>
    block.CreateJsonReportBlock() for block in self.error_devices
  File "/home/ghairapetian/.local/lib/python3.9/site-packages/validate/telemetry_validation_report.py", line 195, in CreateJsonReportBlock
    EXPECTED_POINTS: self._TelemetryPointListToDict(self.expected_points),
  File "/home/ghairapetian/.local/lib/python3.9/site-packages/validate/telemetry_validation_report.py", line 233, in _TelemetryPointListToDict
    point_dictionary = {
  File "/home/ghairapetian/.local/lib/python3.9/site-packages/validate/telemetry_validation_report.py", line 234, in <dictcomp>
    point.point_name: {PRESENT_VALUE_KEY: point.present_value}
AttributeError: 'DimensionalValue' object has no attribute 'point_name'
```

**Expected behavior**
A full validation report with no generating error

**Screenshots**
![image](https://user-images.githubusercontent.com/83808569/221831804-5749ea60-1870-47ec-9113-5aef8b11edca.png)

**OS (please complete the following information):**
Ubuntu

**Additional context**
Nothing to signal

**Comment by trav3711** [comment]
Hi @ghairapetian there is a pull request out to patch this bug. Should be patched by end of week. I will post here once the patch is merged.

**Comment by trav3711** [comment]
Hi @ghairapetian just giving you an update. Our last patch did not entirely fix the bug. I am still looking into this one. Sorry for the delay.

**Comment by trav3711** [comment]
Hi @ghairapetian can you check if your error has been resolved with recent patches made to the code base?

**Comment by charbull** [comment]
@ghairapetian friendly ping :) 
Is this resolved ?

Thank you

**Comment by sypks** [comment]
Hi ghairapetian,

could you please verify that the file located at: digitalbuildigs/ontology/yaml/resources/fields/telemetry_fields.yaml

matches the following for 'scene_index_command'

![image](https://user-images.githubusercontent.com/7757322/226446003-68f617ff-bd83-444e-996d-a8b35e0bc003.png)

**Comment by sypks** [comment]
Hi ghairapetian,

Could you please check the definition for 'scene_index_command' in the telemetry_fields.yaml file located at 'ontology/yaml/resources/fields/telemetry_fields.yaml'?

The definition for the file should look something like the following,
![image](https://user-images.githubusercontent.com/7757322/226469705-3a07d1d7-7a1c-4000-aee5-e221ed7b70ee.png)

If it isn't we'd like to ask that you either download the current version of the repo or perform a git pull from the master branch. In either case please be sure to perform the install process again as some scripts have changes that require this.

**Comment by ghairapetian** [comment]
Hello,
I still can't try. New errors since the git pull.

![image](https://user-images.githubusercontent.com/83808569/226571222-92d348d6-839f-42c8-a160-a5f7bd2b9b03.png)

**Comment by sypks** [comment]
Hello,

Did you pull from the master branch?
The commit https://github.com/google/digitalbuildings/commit/3f093d361d5e8c1c9cb7505ac91fc877749ab831 addresses this issue.

**Comment by sypks** [comment]
Hello @ghairapetian,

We have created a pull request https://github.com/google/digitalbuildings/pull/981 to address this issue. Please wait until this has been merged, then update your branch. We apologize for this.

**Comment by mschulze17** [comment]
@ghairapetian friendly ping on this issue

**Comment by ghairapetian** [comment]
It works, thank you very much !
