### ISSUE TITLE
Error adding new entity types

### ISSUE THREAD

**Issue by kevin-hereworks** [google/digitalbuildings#942]
**IMPORTANT**
DO NOT INCLUDE ANY PROJECT-SPECIFIC INFORMATION IN THIS TICKET!
ANY PROJECT-SPECIFIC CONTEXT (E.G. BUILDING CONFIG INPUTS) SHOULD BE
EMAILED DIRECTLY TO: digitalbuildings-support@googlegroups.com

PLEASE REFERENCE THIS ISSUE LINK IN YOUR EMAIL TO THAT GROUP

**Describe the bug**

Run EndBug/add-and-commit@v9
Running in /home/runner/work/digitalbuildings/digitalbuildings
Add input parsed as single string, running 1 git add command.
> Using 'db-robot <db-robot@google.com>' as author.
> Using "Add GUIDs to new entity types" as commit message.
Internal logs
Outputs
Error: Error: Pushing to https://github.com/kevin-hereworks/digitalbuildings
remote: Permission to kevin-hereworks/digitalbuildings.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/kevin-hereworks/digitalbuildings/': The requested URL returned error: 403

Unable to create entity types since:
Modify ontology validator action to generate type guids 
#934 by jmact17 was merged 2 days ago

**To Reproduce**
1. Create pull request from forked repository adding new entity types to trigger the 'add guids to new entity types'

**Expected behavior**
Permission granted and guids added

**Screenshots**

**OS (please complete the following information):**
Ubuntu

**Additional context**
Not sure if this is on my end but haven't seen any entity types created in the last few days so could be a problem. I have tried reforking, Allow all actions and reusable workflows in settings, have not found anything online to fix over the last few days.

Current PR with this issue:
https://github.com/google/digitalbuildings/pull/941

**Comment by mschulze17** [comment]
@jmact17 mind PTAL and let me know whether to bring into the current board?

**Comment by kevin-hereworks** [comment]
Hi all apologies I should have added this asap as it might not be obvious but to get around this issue in the mean time while using feature branches on forks, the guids should be added manually before making the PR @charbull

**Comment by charbull** [comment]
Hi @kevin-hereworks I patched those manually to avoid blockage. While we are working on a workaround.
it seems all your PRs are from your master branch so it should not be an issue to you

**Comment by charbull** [comment]
@kevin-hereworks this issue is now resolved, thank you for reporting it.
