### ISSUE TITLE
NETWORK (BMS) Namespace Addition

### ISSUE THREAD

**Issue by tasodorff** [google/digitalbuildings#95]
We currently do not model the BMS (or other network) architectures distinctly from the system they control (e.g. HVAC). It may be desirable in certain deployments to model both the devices being controlled and the controllers themselves as separate entities. 

Proposal: Add namespace for BMS (or NETWORK to be less specific) and define types/connections for it.

**Comment by berkoben** [comment]
Thinking aloud, this is analogous to how we modeled secure doors where we had a master entity with  has_part connections to subcomponents:  We'd want some type like NETWORKED_HVAC_DEVICE that must have a has_part connection to an EQUIPMENT and a NETWORK_CONTROLLER.  So generally, yes, I support this.

**Comment by mschulze17** [comment]
Closed per review with Trevor
