### ISSUE TITLE
QUDT link broken

### ISSUE THREAD

**Issue by sypks** [google/digitalbuildings#953]
**IMPORTANT**
DO NOT INCLUDE ANY PROJECT-SPECIFIC INFORMATION IN THIS TICKET!
ANY PROJECT-SPECIFIC CONTEXT (E.G. BUILDING CONFIG INPUTS) SHOULD BE
EMAILED DIRECTLY TO: digitalbuildings-support@googlegroups.com

PLEASE REFERENCE THIS ISSUE LINK IN YOUR EMAIL TO THAT GROUP

**Describe the bug**
QUDT link in README broken at thttps://github.com/google/digitalbuildings/tree/master/ontology/docs/ontology.md

**Comment by charbull** [comment]
@sypks https://www.qudt.org/

**Comment by sypks** [comment]
thank you!
