### ISSUE TITLE
TELEMETRY VALIDATION HELP REQUIRED

### ISSUE THREAD

**Issue by darshanjain12** [google/digitalbuildings#955]
**IMPORTANT**
DO NOT INCLUDE ANY PROJECT-SPECIFIC INFORMATION IN THIS TICKET!
ANY PROJECT-SPECIFIC CONTEXT (E.G. BUILDING CONFIG INPUTS) SHOULD BE
EMAILED DIRECTLY TO: digitalbuildings-support@googlegroups.com

PLEASE REFERENCE THIS ISSUE LINK IN YOUR EMAIL TO THAT GROUP

**Describe the bug**
During the telemetry validation facing an error,Top-level exception occurred in callback while processing a message

Traceback (most recent call last):
  File "C:\digitalbuildings\tools\tooling\Lib\site-packages\google\cloud\pubsub_v1\subscriber\_protocol\streaming_pull_manager.py", line 126, in _wrap_callback_errors
    callback(message)
  File "C:\digitalbuildings\tools\tooling\Lib\site-packages\validate\telemetry_validator.py", line 200, in ValidateMessage
    validation_block.description += (
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
[ERROR] Pub/sub subscription failed with error: unsupported operand type(s) for +=: 'NoneType' and 'str'

On seeing logs found it to be subscribing to a payload and not to the events payload. 

**Note : All the  state and  events payload are UDMI compliant**

**To Reproduce**
1. Setting up cloud subscription '...'
2. Giving a command: python toolkit.py -i file path -v -s topic-subscription --udmi
3. Scroll down to last

![image](https://user-images.githubusercontent.com/104188629/224527626-94c67ae9-a2cc-41c4-ab00-9e274e865d8b.png)

**Comment by trav3711** [comment]
Hi @darshanjain12 could you try running the `pip_install` script again? I think you may be using an out-dated/broken version of the telemetry validator.

**Comment by darshanjain12** [comment]
HI @trav3711 tried running this error got resolved. But now the telemetry validator is subscribing to the state payloads and giving errors

**Comment by tasodorff** [comment]
@darshanjain12 we are checking with UDMI team on this. Will respond ASAP.

**Comment by charbull** [comment]
Hi @darshanjain12 can you please share the topic you used for validation at this email: `digitalbuildings-support@googlegroups.com` please also specify this issue number/link.

thank you

**Comment by tasodorff** [comment]
@darshanjain12 after discussing internally, the appropriate fix is to remove state messages from this topic. the telemetry validator does not support topics with state messages on them, and this will be the case for the near future. if you have any questions about this specifically regarding your project, please reach out to your project lead or to udmi-discuss@googlegroups.com. Thanks
