### ISSUE TITLE
MERGE PULLREQUEST HELP REQUIRED

### ISSUE THREAD

**Issue by darshanjain12** [google/digitalbuildings#962]
Hi Team raising issue for a help in Merging our pull request which was approved long back.

At the time of approval it has passed all validators.
I am not able to figure out what went wrong due to some changes could you please help me merging both pull requests.
Pull Request: https://github.com/google/digitalbuildings/pull/871 &  https://github.com/google/digitalbuildings/pull/883

![image](https://user-images.githubusercontent.com/104188629/225285736-f69e2461-3cea-40ab-ba01-9193f5d7f8db.png)

**Comment by jmact17** [comment]
This PR should have fixed the issue: https://github.com/google/digitalbuildings/pull/964/files

**Comment by charbull** [comment]
Hi @darshanjain12 
The RP resolved it partially, 

Please see here; https://github.com/google/digitalbuildings/issues/942#issuecomment-1463743451 for a resolution.

We created a bug to update the guid generation on PRs coming from feature branches
