### ISSUE TITLE
TELEMETRY-VALIDATION-UDMI-PAYLOAD-ERROR

### ISSUE THREAD

**Issue by darshanjain12** [google/digitalbuildings#994]
Hi Team,

Raising this issue for the help required clearing the error in telemetry validation with "description": "[ERROR]\tMessage for LMP-23 does not conform to UDMI standard."

Attached the snapshot from telemetry validation
![image](https://user-images.githubusercontent.com/104188629/228772577-dae728d6-2565-49aa-ba4d-ab439c8e60ef.png)

The  UDMI validator has been passing the validation for the above entity but giving us error here in telemetry validator please help us know the reason so that we can work on clearing the error .Attached the snapshots from UDMI.

![image](https://user-images.githubusercontent.com/104188629/228775335-8d03d00b-6980-499b-a215-ef9982a3c8b9.png)

![Screenshot from 2023-03-30 13-53-26](https://user-images.githubusercontent.com/104188629/228775622-160f0349-8c1a-4de9-9f77-d0050492e6ee.png)
![Screenshot from 2023-03-30 13-53-06](https://user-images.githubusercontent.com/104188629/228775831-976d95a4-176c-42b5-8f0b-f7cb5058c390.png)

**Comment by charbull** [comment]
@darshanjain12 can we close this one ? or it still blocking you?

**Comment by darshanjain12** [comment]
Still facing this issue

**Comment by trav3711** [comment]
Hi @darshanjain12 the issue should be resolved now. Closing issue.
