### ISSUE TITLE
TELEMETRY VALIDATOR SHOWING MISSING DEVICES FOR DEVICES ONLINE ON CLOUD

### ISSUE THREAD

**Issue by darshanjain12** [google/digitalbuildings#996]
Hi Digital Buildings Team,

Raising this issue to seek support for the telemetry validation results showing that the devices seems missing.
The device mentioned in the report are actually available on cloud & are online & sending data.
Attached the snapshot from cloud as well as the UDMI payload being recieved from cloud.

![image](https://user-images.githubusercontent.com/104188629/228815363-a8e99c4f-6793-465d-89a7-a0e3a0840298.png)

![image](https://user-images.githubusercontent.com/104188629/228816074-75010365-1f71-4bb2-8eb7-b00d0210c361.png)

**Comment by trav3711** [comment]
Hi @darshanjain12 clarifying question: Are these devices reporting telemetry in the event_poinset.json payload? For Our telemetry validator to consider devices `valid`, they must be reporting telemetry and not just states.

**Comment by darshanjain12** [comment]
@trav3711  Yes they are reporting the telemetry in the event_pointset.json payload.

**Comment by trav3711** [comment]
Hey @darshanjain12 are you still facing this same bug or were you able to resolve it?

**Comment by darshanjain12** [comment]
@trav3711 I am not able to resolve this issue.
Required snapshot attached.

![image](https://user-images.githubusercontent.com/104188629/231355833-a9e3a4f7-5cd9-443d-be21-df8c8e072108.png)

**Comment by trav3711** [comment]
Hi Darshain, can you provide the command you ran in order to surface this error? I'm trying to re-create the error.

**Comment by darshanjain12** [comment]
Command I ran was.
python3 toolkit.py -i filepath -v -s projects/project-id/subscriptions/projectname-subscription --udmi

**Comment by trav3711** [comment]
Resolution is to increase the timeout duration for the telemetry validator using the `--timeout` flag. Since some buildings have a large amount of devices, the telemetry validator needs more time to listen to the pubsub stream in order to capture them all.
